name: datasci
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.8.1
  - black=19.10b0
  - ipython=7.10.1
  - isort=4.3.21
  - jinja2=2.10.3
  - jupyterlab=2.0.1
  - markdown=3.1.1
  - matplotlib=3.1.2
  - mypy_extensions=0.4.3
  - notebook=6.0.1
  - numpy=1.17.3
  - pandas=0.25.3
  - pygments=2.5.2
  - pylint=2.4.4
  - pytest=5.3.1=
  - pytest-cov=2.8.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - statsmodels=0.11.1

